name: Ping Replit

on:
  schedule:
    - cron: '*/15 * * * *'  # 每15分钟执行一次

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping application
        run: curl -s https://1cbd735c-f067-4dd3-a1ad-4c3ccd8036f0-00-zer0ov627xrj.sisko.replit.dev/ > /dev/null
